### PR TITLE
sorting on package/file level

### PR DESCRIPTION
**Pull request by tehsphinx**
Sorts declarations in a file:
1. by type in the following order: `unknown`, `imports`, `consts`, `vars`, `funcs`
2. by code block size (bigger first)

### CODE REVIEW

**Comment by junedev** [comment]
@tehsphinx Isn't `type` also one of the "top level" keywords to consider in the sorting? :thinking:

**Comment by tehsphinx** [comment]
Right, will look into it.

**Comment by tehsphinx** [comment]
`type` added for sorting

**Comment by junedev** [comment]
I don't understand every detail of the code but looks rather straight forward and according to the test cases it works as expected, so I approved.

**Comment by junedev** [comment]
@exercism/maintainers-admin Reminder that this still needs approval (the representer is not in use yet so it is low risk).

**Pull request merged**
